import { Metadata } from "next";
import SuccessStoryInnerPage from "@/components/blocks/success-stories/inner-page-layout/success-story-inner-page-design";
import { SuccessStoryContentType } from "@/components/blocks/success-stories/inner-page-layout/success-story-inner-page-grid-layout";

//Metadata
export const metadata: Metadata = {
  title: "Infoveave Empowers CRS's Food Monitoring in Ethiopia",
  description: "Infoveave's Enhanced Analytics power Project Balance, to assist CRS food monitoring with advanced risk management system for the JEOP.",
  robots: {
    index: true,
    follow: true,
  },
  openGraph: {
    locale: "en_US",
    type: "article",
    title: "Infoveave Empowers CRS's Food Monitoring in Ethiopia",
    description: "Infoveave's Enhanced Analytics power Project Balance, to assist CRS food monitoring with advanced risk management system for the JEOP.",
    url: "https://infoveave.com/infoveave-collaborates-with-project-balance-catholic-relief-services-csr/",
    siteName: "Infoveave",
    images: [
      {
        url: "https://i0.wp.com/infoveave.com/wp-content/uploads/2023/01/Infoveave-Flower-Logo.png?fit=237%2C212&ssl=1",
        width: 2240,
        height: 1260,
        type: "image/jpeg",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Est. reading time",
  },
};

//Content Area
const successStoryHeading = "Infoveave collaborates with |Project Balance & Catholic Relief Services| (CRS)";

const successStoryContent: SuccessStoryContentType[] = [
  {
    id: 0,
    image: { image: "https://infoveave.com/wp-content/uploads/2022/10/Project-Balance-Logo-Cropped.svg", className: "w-full md:w-[250px] mt-0 md:mt-[-20px]" },
  },
  {
    id: 1,
    heading: "Ethiopia Joint Emergency Operation Program (JEOP)",
    paragraph:
      "In an article published on ICTWorks.org, Catholic Relief Services (CRS) has highlighted the Joint Emergency Operation’s (JEOP) highly effective food monitoring program in Ethiopia. Millions of people are served by this initiative of food distribution, based on monitoring the “last-mile data” . To identify and manage risk and compliance variables such as warehouse and market location, warehouse management, and local distribution channels, field-based data was used to construct a risk management model. In addition to identifying social and environmental conditions like political unrest, community location, and other elements that may call for closer management of resources, CRS could use the risk index generated by the system to decide where to relocate personnel and other resources in order to proactively prevent losses. CRS hired Project Balance to create a system that pulls monitoring data gathered on tablets in the field, detects data discrepancies, offers a work flow for data approval, and shows risk and other monitoring data in a series of dashboards.",
  },
  {
    id: 2,
    heading: "Contribution by Infoveave ",
    paragraph:
      "CRS relied on the iFormBuilder cloud data repository to pull data from the filed, which is then transformed and placed into a data warehouse. Additionally, data is validated and approved by the data management application. After then, the data was moved to the Infoveave – Data Intelligence Platform. The data was engineered, analyzed and visualized over the Infoveave platform. The business intelligence tool Infoveave created a comprehensive dashboard system for administering the program by displaying a variety of data visualizations, such as maps, graphs, tables, and text widgets. The data was presented back to the management with insightful visualizations and in a clean and easy to understand manner.",
    image: "https://projectbalance.com/wp-content/uploads/2017/11/ICT4D-process.png",
  },
  {
    id: 3,
    heading: "About Infoveave",
    paragraph: "Infoveave® provides insights to stakeholders by transforming data into visual and actionable information. Users of Infoveave® can",
    bulletPoints: [
      "Load data sources using an easy-to-use wizard.",
      "Create visual mashups from an array of interactive data visualisation options.",
      "Perform analysis and correlations across many data sources.",
      "Carry out Competitor Analysis, Customer Analysis, MTD, YTD Trends Analysis.",
      "Track Operational Efficiency & Effectiveness Risk & Compliance.",
      "Simulate What-if scenarios, Forecast and Predict trends on large datasets.",
      "Build historical data, discover patterns and gather deeper insights on demand.",
      "Share and collaborate with stakeholders and customers for quick action.",
    ],
  },
];

const ProjectBalanceCatholicReliefServicesCRS = () => {
  return <SuccessStoryInnerPage heading={successStoryHeading} content={successStoryContent} />;
};

export default ProjectBalanceCatholicReliefServicesCRS;
