import salesKpi from "@/assets/kpi-liabrary/top-10-sales-kpis-to-track.webp";
import KpisInnerPage from "@/components/blocks/kpis/inner-page-layout/kpi-inner-page-design";
import { kpisContentType } from "@/components/blocks/kpis/inner-page-layout/kpis-inner-page-grid-layout";
import { generatemetadata } from "@/metadata/utils/generate";

export const dynamic = "force-dynamic";

// eslint-disable-next-line @typescript-eslint/no-unused-vars
const revalidate = 10;
export const runtime = "edge";
export async function generateMetadata() {
  return generatemetadata("top-10-sales-kpis-to-track");
}

const top10SalesKpisHeading = "|Sales| KPIs to track";

const top10SalesKpisContent: kpisContentType[] = [
  {
    paragraph: [
      "Explore essential Sales Key Performance Indicators (KPIs) that businesses utilize to measure and optimize their sales performance. These metrics provide valuable insights into various aspects of sales operations, from revenue generation and profitability to customer behavior and inventory management. By tracking and analysing these KPIs, businesses can make informed decisions, improve efficiency, and enhance overall sales effectiveness. Whether it’s understanding customer traffic, evaluating inventory turnover, or optimizing average transaction values, these KPIs play a critical role in driving growth and success in sales strategies.",
    ],
  },
  {
    heading: "Why is sales KPI important?",
    paragraph: [
      "KPIs are crucial for businesses as they offer measurable metrics to assess the effectiveness and efficiency of sales strategies and operations. By tracking these KPIs, businesses can gauge their revenue generation, customer acquisition, and profitability performance. Sales KPIs offer a comprehensive framework for evaluating sales performance, driving profitability, and ensuring alignment with business objectives, empowering businesses to make informed decisions and maintain a competitive edge in the market.",
    ],
  },
  {
    heading: "10 Important sales KPIs to track",
    bulletPoints: [
      {
        listHeading: "1. Net sales",
        listParagraph: [
          "Net sales represent the total revenue generated by a company from its primary business activities after accounting for discounts and allowances. This metric is crucial for evaluating a company’s financial performance as it provides a clear picture of the actual revenue earned from sales, excluding any reductions or concessions. By focusing on net sales, businesses can accurately assess the effectiveness of their sales strategies and pricing policies. This metric helps in identifying trends in customer behavior, such as the impact of discounts on sales volumes.",
        ],
        formula: "Net Sales = Sales – Discounts – Allowances",
      },
      {
        listHeading: "2. Gross profit margin",
        listParagraph: [
          "Gross profit margin is the percentage of revenue retained by a company after deducting the cost of goods sold from its net sales revenue. This metric is vital for businesses as it provides insight into how efficiently they are producing and selling their products.",
          "A higher gross profit margin shows that a company can retain more revenue from each sale, which can be reinvested into the business for growth initiatives such as marketing, research and development, or expanding operations.",
          "A lower margin shows rising production costs or pricing pressures that need to be addressed to maintain profitability.",
        ],
        formula: "Gross Profit Margin = ((Net sales – Cost of goods sold) / Net sales) x 100",
      },
      {
        listHeading: "3. Net profit",
        listParagraph: [
          "The money that remains in a business after all costs, including as operational expenses, taxes, interest, and depreciation, have been met is known as net profit. This is crucial for businesses as it provides a clear picture of their financial health and overall performance.",
          "Net profit reflects the company’s ability to generate profits from its core operations. Regularly monitoring and analyzing net profit enables businesses to identify trends, and spot potential issues early, ensuring long-term sustainability and growth.",
        ],
        formula: "Net Profit = Sales – Expenses",
      },
      {
        listHeading: "4. Net profit margin",
        listParagraph: [
          "The portion of income that is left over as profit after all costs have been paid is known as the net profit margin. This metric is essential for businesses as it provides a comprehensive view of their profitability. By showing how efficiently a company can generate profit from its operations and manage its expenses.",
          "A higher net profit margin shows that a company is effectively controlling its costs and maximizing its revenue, which can lead to greater financial stability and growth.",
          "A lower net profit margin shows the need for cost reduction, process improvement, or pricing strategy adjustments.",
        ],
        formula: "Net Profit Margin = (Net profit / Sales) x 100",
      },
      {
        listHeading: "5. Average order value",
        listParagraph: [
          "The average amount of money spent by customers per order. Tracking average order value helps businesses understand customer spending habits, identify opportunities for upselling or cross-selling, optimize pricing strategies, and increase overall revenue.",
          "Increasing the average order value ultimately boosts overall revenue, making it a key focus for businesses aiming to enhance their financial performance and growth. Regularly monitoring average order value enables businesses to implement targeted marketing and sales strategies, tailor their product offerings, and improve the overall customer experience.",
        ],
        formula: "Average Order Value = Sales / Number of orders",
      },
      {
        listHeading: "6. Sell through rate",
        listParagraph: [
          "The most important metric for organizations is the sell-through rate, which is the proportion of inventory sold during a certain period relative to the total inventory available for sale.",
          "A high sell-through rate shows that products are moving quickly, suggesting effective pricing, strong demand, and successful marketing efforts.",
          "A low sell-through rate shows issues such as overstocking, inadequate marketing, or misaligned pricing strategies.",
        ],
        formula: "Sell Through Rate = (Number of units sold / Beginning inventory) x 100",
      },
      {
        listHeading: "7. Conversion rate",
        listParagraph: [
          "The conversion rate measures the percentage of website visitors or potential customers who complete a desired action, such as making a purchase or subscribing to a service. This metric is crucial for evaluating the effectiveness of a business’s online presence and marketing strategies.",
          "A high conversion rate shows that a percentage of users are interacting with the website and completing the intended tasks, demonstrating the efficiency of the advertising campaigns.",
          "A low conversion rate shows potential issues such as poor ineffective marketing, or a misalignment between the product offerings and customer expectations.",
        ],
        formula: "Conversion Rate = (Number of sales / Number of stores)",
        listImage: salesKpi,
      },
      {
        listHeading: "8. Return rate",
        listParagraph: [
          "The return rate is the percentage of products purchased by customers that are subsequently returned to the business within a specific period. This metric helps businesses assess the extent of product returns, providing insights into customer satisfaction, product quality, and the accuracy of product descriptions.",
          "A high return rate shows issues such as poor product quality, misleading marketing, or a disconnect between customer expectations and the actual product.",
          "A low return rate shows that customers are generally satisfied with their purchases, reflecting positively on product quality and marketing accuracy.",
        ],
        formula: "Return Rate = (Number of returns / Number of units sold) x 100",
      },
      {
        listHeading: "9. Average inventory",
        listParagraph: [
          "Average inventory is a metric that represents the average quantity and value of materials or products held in stock over a specified period, typically a month, quarter, or year. It serves as a crucial tool for businesses to manage their inventory levels effectively and optimize operational efficiency.",
          "By calculating average inventory, businesses can mitigate the impact of seasonal fluctuations or unexpected changes in demand, ensuring that they maintain adequate stock levels to meet customer demands without overstocking.",
        ],
        formula: "Average Inventory = (Beginning inventory + Ending inventory) / 2",
      },
      {
        listHeading: "10. Inventory turnover ratio",
        listParagraph: [
          "The inventory turnover ratio is a crucial metric that measures how efficiently a company manages its inventory by comparing the cost of goods sold to the average inventory level maintained during a specific period. It provides valuable insights into how quickly a company’s inventory is sold and replaced over time.",
          "A high inventory turnover ratio shows that a company is effectively selling its inventory and replenishing it promptly, which can lead to improved cash flow and reduced carrying costs.",
          "A low ratio shows overstocking or slow-moving inventory, which ties up capital and may lead to obsolescence or storage costs.",
        ],
        formula: "Inventory Turnover Ratio = Cost of goods sold / Average inventory",
      },
    ],
  },
];

const formHeading = "Get the complete list of Sales KPIs";

const Top10KPIForSales = () => {
  return <KpisInnerPage heading={top10SalesKpisHeading} content={top10SalesKpisContent} formHeading={formHeading} />;
};

export default Top10KPIForSales;
