import BlogsInnerPage from "@/components/blocks/blogs/inner-page-layout/blog-inner-page-design";
import { generatemetadata } from "@/metadata/utils/generate";
export const dynamic = "force-dynamic";
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const revalidate = 10;
export const runtime = "edge";
export async function generateMetadata() {
  return generatemetadata("sales-dashboards-metrics-to-track-benefits-best-practices");
}

//Content Area
const blogHeading = "How can a |unified data platform| help retailers with automation?";

const blogContent = [
  {
    id: 1,
    subHeading: "Sales dashboards: metrics & best practices",
    paragraph:
      "Sales teams need to utilize the power of data to stay ahead of the competition. Business Intelligence dashboards provide a comprehensive view of critical sales metrics, customer behaviours, and product performance, enabling sales teams to make informed decisions and optimize their strategies. Infoveave offers solutions to empower sales teams with real-time insights.",
  },
  {
    id: 2,
    paragraph:
      "This blog explores how dashboards, such as sales and revenue, product performance, customer churn, and sales analysis dashboards, can empower sales teams to drive revenue growth and improve overall performance.",
  },
  {
    id: 3,
    heading: "What are the types of dashboards that sales teams need?",
    list: ["Sales and revenue dashboard"],
    listImage: "https://i0.wp.com/infoveave.com/wp-content/uploads/2024/08/Sales-and-Revenue-Dashboard.png?w=743&ssl=1",
    paragraph:
      "The sales and revenue dashboard provides a holistic view of sales performance. By tracking sales and revenue trends across various channels and regions, sales teams can identify successful strategies and replicate them. Understanding customer preferences and purchasing behaviors helps in tailoring marketing campaigns and product offerings, leading to increased sales and customer satisfaction.",
    bulletPoints: [
      "Sales:| Tracks the total number of products sold within a specific period.",
      "Sales by channel:| Measures the distribution of sales across different sales channels online and offline.",
      "Revenue trend:| Displays the pattern of revenue generation over a specific period.",
      "Revenue by country:| Shows the total revenue generated from sales in each country.",
      "Total sales by product name:| Tracks the total number of units sold for each product name.",
      "Customers by product category:| Measures the number of unique customers purchasing products within each category.",
    ],
  },
  {
    id: 4,
    list: ["Customer churn dashboard"],
    listImage: "https://i0.wp.com/infoveave.com/wp-content/uploads/2024/08/Customer-churn-dashboard.png?w=741&ssl=1",
    paragraph:
      "The customer churn dashboard helps sales teams understand why customers leave and develop strategies to retain them. By monitoring churn rates and revenue impacts, teams can proactively address issues and improve customer loyalty. Tracking MRR growth and CLV provides insights into long-term customer value, helping prioritize efforts on high-value customers.",
    bulletPoints: [
      "Churn rate:| Tracks the percentage of customers who stop using your product or service during a given period.",
      "Premium users:| Indicates the percentage of customers who have opted for premium services or subscriptions.",
      "Customer retention rate:| Measures the percentage of existing customers who remain with your company over a specific period.",
      "Customer loyalty rate:| Reflects the percentage of customers who repeatedly purchase or engage with your product or service.",
      "Revenue churn:| Calculates the percentage of revenue lost due to customer churn over a specific period.",
      "Revenue generated per user:| Shows the average revenue generated by each customer over a specific period.",
      "Monthly recurring revenue (MRR) growth:| Indicates the increase or decrease in monthly recurring revenue over time.",
      "Customer lifetime value (CLV):| Estimates the total revenue a business can reasonably expect from a single customer account throughout its business relationship.",
    ],
  },
  {
    id: 5,
    list: ["Sales analysis dashboard"],
    listImage: "https://i0.wp.com/infoveave.com/wp-content/uploads/2024/08/Sales-analysis-dashboard.png?w=742&ssl=1",
    paragraph:
      "The sales analysis dashboard provides detailed insights into the sales process. By tracking orders, revenue, and profit, sales teams can assess overall performance and identify profitable areas. Understanding shipping costs and handling charges helps optimize logistics and reduce expenses. Analyzing orders by category and product profitability guides inventory management and marketing strategies.",
    bulletPoints: [
      "Orders:| Represents the total number of orders placed by customers within a specific period.",
      "Revenue:| Shows the total income generated from sales within a given period.",
      "Profit:| Reflects the net income after subtracting the cost of goods sold and other expenses from the total revenue.",
      "GST percentage:| Indicates the percentage of goods and services tax applied to sales.",
      "Handling charge:| Tracks the total amount charged for handling and processing orders.",
      "Shipping cost:| This represents the average cost incurred for shipping products to customers.",
      "Shipping TAT:| Measures the average turnaround time for shipping orders to customers.",
      "Orders by category:| Displays the distribution of orders across different product categories (e.g., Baby Food, Cosmetics).",
      "Product profitability:| Shows the profit margin for different products, indicating their financial performance.",
    ],
  },
  {
    id: 6,
    list: ["Product performance dashboard"],
    listImage: "https://i0.wp.com/infoveave.com/wp-content/uploads/2024/08/Product-performance-dashboard.png?w=745&ssl=1",
    paragraph:
      "The product performance dashboard allows sales teams to assess the financial performance of individual products. By tracking sales and profitability across categories and types, teams can identify high-margin items and optimize pricing strategies. Monitoring shipping costs and sales channels helps streamline distribution and maximize revenue.",
    bulletPoints: [
      "Price:| Indicates the total sales price of all products sold within a specific period.",
      "Profit:| This represents the net profit after subtracting the total cost from the total sales price.",
      "Unit price by top 10 products:| Displays the unit price of the top 10 best-selling products.",
      "Sales by product category:| This shows the volume of sales for each product category.",
      "Revenue by product category:| Indicates the total revenue generated from each product category.",
      "Sales by product type:| Tracks the distribution of sales across different product types (e.g., packet, jar).",
      "Shipping cost over time period:| Measures the shipping costs incurred over a specific period.",
      "Total sales by sales channel:| Compares the total sales generated from different sales channels (e.g., online, offline).",
    ],
  },
  {
    id: 7,
    heading: "What are the best practices to build an effective sales dashboard?",
    list: ["Define clear objectives"],
    paragraph:
      "Before creating a sales dashboard, it’s essential to define clear objectives and goals. Understand what key metrics and KPIs are most important for your sales team. Infoveave allows you to customize your dashboard to ensure that it provides relevant and actionable insights tailored to your specific needs.",
  },
  {
    id: 8,
    list: [" Keep it simple and user-friendly"],
    paragraph:
      "An effective sales dashboard should be intuitive and easy to navigate. Infoveave’s user-friendly interface makes it simple to use clear visualizations like bar charts, line graphs, and pie charts to present data. Avoid clutter by focusing on the most critical metrics and using filters to allow users to drill down into the data as needed.",
  },
  {
    id: 9,
    list: ["Ensure data accuracy and timelines"],
    paragraph:
      "The value of a sales dashboard depends on the accuracy and timeliness of the data it presents. Infoveave implements robust data integration processes to ensure that the dashboard is updated in real time with accurate information. Regularly validate the data sources and set up automated alerts for any discrepancies.",
  },
  {
    id: 10,
    heading: "How Infoveave can help Sales Teams?",
    list: ["Enhanced decision-making"],
    paragraph:
      "Infoveave’s designer dashboards allow sales teams to create highly customized visualizations tailored to their specific needs. This feature enables teams to focus on the most critical metrics and KPIs, providing a clear and concise overview of their sales performance. By having a tailored view, sales managers can make more informed decisions, quickly identify trends, and respond to market changes with agility.",
  },
  {
    id: 11,
    list: ["Get deeper insights into your data easily"],
    paragraph:
      "The drill-down capability in Infoveave dashboards allows sales teams to delve deeper into their data, uncovering detailed insights that might not be immediately apparent. This feature enables users to click through layers of data to explore underlying factors and root causes of trends or anomalies. For example, if a sales report shows a dip in revenue, a drill-down might reveal that it’s due to decreased sales in a specific region or product category. By providing this granular level of analysis, sales teams can understand the nuances of their performance, identify areas for improvement, and develop targeted strategies to enhance customer retention and satisfaction.",
  },
  {
    id: 12,
    list: ["Optimized sales performance with board expressions"],
    paragraph:
      "Infoveave’s board expressions are similar to conditional formatting but offer enhanced capabilities such as changing icons, colors, and setting up alerts. This feature allows sales teams to visually highlight important data points and trends, making it easier to spot opportunities and potential issues. Customizing the appearance of data helps in prioritizing actions, improving response times, and optimizing overall sales performance.",
  },
  {
    id: 13,
    list: ["Real-time insights for proactive management"],
    paragraph:
      "Infoveave dashboards offer real-time data integration, ensuring that sales teams always have access to the most up-to-date information. This immediacy allows teams to respond proactively to emerging trends, address potential issues before they escalate, and capitalize on new opportunities as they arise. Real-time insights facilitate a more dynamic and responsive sales strategy.",
  },
  {
    id: 14,
    list: ["Streamlined reporting and communication"],
    paragraph:
      "With Infoveave, sales teams can automate the generation of regular reports, reducing the time and effort required for manual reporting. These automated reports can be customized and scheduled to ensure that stakeholders receive timely and relevant information. Streamlined reporting enhances internal communication, ensuring that all team members and management are aligned and informed.",
  },
  {
    id: 15,
    paragraph:
      "Dashboards offered by Infoveave, are essential tools for sales teams, providing real-time, actionable insights that drive better decision-making and strategic planning. By leveraging Infoveave dashboards like sales and revenue, customer churn, sales analysis, and product performance, sales teams can enhance their performance, and improve customer retention.",
  },
];

const SalesDashboard = () => {
  return <BlogsInnerPage heading={blogHeading} content={blogContent} />;
};

export default SalesDashboard;
